[book]
title = "The Book Which Tells The Truth"
authors = ["Rael"]
description = "Web book of Rael's first publication."
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fa-github"

